### ISSUE TITLE
hvac.exceptions.InvalidPath: None

### ISSUE THREAD

**Issue by rforberger** [hvac/hvac#1115]
I tried the following code:

```
#!/usr/bin/python3

import hvac
import json

mountpoint = "security"

client = hvac.Client(
  url='http://localhost:8200',
  token="hvs.",
)

# list
paths = client.list(mountpoint)
pathlist = paths['data']['keys']

for path in pathlist:
  list_of_secrets = client.secrets.kv.v1.list_secrets(mount_point=mountpoint,path=path)

  secrets = client.secrets.kv.v1.read_secret(
    path=path,
    mount_point=mountpoint,
  )
  #for secretname in list_of_secrets:
#  secret = secrets.read_secret_result['data'][secretname]
#  fields = json.loads(secret).keys()
#  for field in fields:
#    value =
#    print(folder,1,login,secretname,,,0,secretname,"$key_inner","$destvalue",")
```

Path structure:

```
AI/
Allgemein/
Apartments/
Arzt/
Banking/
Cloud/
DevOps/
Domains/
Elster/
Employers/
Entwicklung/
Freizeit/
Geräte/
GnuPG/
Google/
Hosting/
Internetdienste/
Netzwerk/
Pass/
Passphrases/
Passwordmanagers/
Payment/
Phone/
Recruiting/
Schufa/
Security/
Server/
Shops/
System/
Telco/
Testinstallationen/
Userpasswörter/
Verwaltung/
```

I get the following error:

```Traceback (most recent call last):
  File "/Users/ronnyforberger/IdeaProjects/bitwarden/./migration.py", line 20, in <module>
    secrets = client.secrets.kv.v1.read_secret(
  File "/Users/ronnyforberger/Library/Python/3.9/lib/python/site-packages/hvac/api/secrets_engines/kv_v1.py", line 32, in read_secret
    return self._adapter.get(
  File "/Users/ronnyforberger/Library/Python/3.9/lib/python/site-packages/hvac/adapters.py", line 146, in get
    return self.request("get", url, **kwargs)
  File "/Users/ronnyforberger/Library/Python/3.9/lib/python/site-packages/hvac/adapters.py", line 408, in request
    response = super().request(*args, **kwargs)
  File "/Users/ronnyforberger/Library/Python/3.9/lib/python/site-packages/hvac/adapters.py", line 376, in request
    self._raise_for_error(method, url, response)
  File "/Users/ronnyforberger/Library/Python/3.9/lib/python/site-packages/hvac/adapters.py", line 294, in _raise_for_error
    utils.raise_for_error(
  File "/Users/ronnyforberger/Library/Python/3.9/lib/python/site-packages/hvac/utils.py", line 41, in raise_for_error
    raise exceptions.VaultError.from_status(
hvac.exceptions.InvalidPath: None, on get http://localhost:8200/v1/security/AI
```

**Comment by rforberger** [comment]
Solved differently.
