### ISSUE TITLE
Python HVAC client  permission denied

### ISSUE THREAD

**Issue by dharamb** [hvac/hvac#185]
client = hvac.Client(url='https://secrets.ourcompany.com:8200',token='2feef0f0-8cc5-ca9d-c1e6-e841d575531d',verify='/etc/ssl/certs/ca-bundle.crt')

client.write('v1/ourcompant/SelfService/PR000360/ap111433/nonprod/secrets/snake', type='pythons', lease='1h')

but keep on getting 403 permission denied error. Same token through postman works fine. Any insight if I need to tweak the URL /port or address where to write the secrets?

**Comment by dharamb** [comment]
Jeff, thanks for replying. I had the same issue while using CLI but figured vault server lagging client version was making calls to a distorted path.Fixing that made CLI work..Not sure if similar issue is with python client but below is stacktrace
 
For python client this is error
Traceback (most recent call last): 
File "<stdin>", line 1, in <module> 
File "/home/a528918/.local/lib/python2.7/site-packages/hvac/v1/__init__.py", line 64, in write 
response = self._put('/v1/{0}'.format(path), json=kwargs, wrap_ttl=wrap_ttl) 
File "/home/a528918/.local/lib/python2.7/site-packages/hvac/v1/__init__.py", line 1242, in _put 
return self.__request('put', url, **kwargs) 
File "/home/a528918/.local/lib/python2.7/site-packages/hvac/v1/__init__.py", line 1278, in __request 
self.__raise_error(response.status_code, text, errors=errors) 
File "/home/a528918/.local/lib/python2.7/site-packages/hvac/v1/__init__.py", line 1288, in __raise_error 
raise exceptions.Forbidden(message, errors=errors) 
hvac.exceptions.Forbidden: permission denied

**Comment by jeffwecan** [comment]
@dharamb: Assuming this is still an issue for you, try dropping the "v1/" prefix from the path parameter when calling `hvac.Client.write()`. That part of the URL is already prepended by that method. Ref: https://github.com/hvac/hvac/blob/5f92583ccf97d6bbea60b1f67c4ae3e7240c29c1/hvac/v1/__init__.py#L189

**Comment by dharamb** [comment]
Had figured that out but many thanks!

**Comment by jeffwecan** [comment]
@Hari4AMQ: The original issue @dharamb ran into was including the API prefix (i.e., `/v1/...`) in their `write()` call. In any case, if you can share your usage that would help determine what is going on in your case.

**Comment by meet101** [comment]
@jeffwecan  - hey, I am having similar issue. new to vault. can you check what am I missing?

>>> import hvac
>>> client = hvac.Client(url="http://<vaultserver>:8200", token="xxx-xxx-xxxx")
>>> client.write('secret/foo', baz='bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hvac/v1/__init__.py", line 227, in write
    response = self._adapter.post('/v1/{0}'.format(path), json=kwargs, wrap_ttl=wrap_ttl)
  File "/usr/local/lib/python2.7/dist-packages/hvac/adapters.py", line 106, in post
    return self.request('post', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hvac/adapters.py", line 265, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/usr/local/lib/python2.7/dist-packages/hvac/utils.py", line 33, in raise_for_error
    raise exceptions.Forbidden(message, errors=errors)
hvac.exceptions.Forbidden: permission denied

**Comment by jeffwecan** [comment]
Note: any discussion on the above comment can be had in the currently open issue: https://github.com/hvac/hvac/issues/349.
