### ISSUE TITLE
Python 2.6 incompatibility after 0.5.0

### ISSUE THREAD

**Issue by zhogov** [hvac/hvac#231]
Following line is not compatible with Python 2.6, but works with Python 2.7:

https://github.com/hvac/hvac/blob/fa44c68a7ad1f38eaba3002f960ae62828c112b0/hvac/v1/__init__.py#L1111

Command used:
```
ansible -vvvvv -m debug -a msg="{{ lookup('hashi_vault', 'secret=path:contents token=my-token url=https://vault.my-company.net') }}" localhost
```
Error message:
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/lib/python2.6/site-packages/ansible/executor/task_executor.py", line 506, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.6/site-packages/ansible/playbook/task.py", line 260, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.6/site-packages/ansible/playbook/base.py", line 390, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.6/site-packages/ansible/template/__init__.py", line 525, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.6/site-packages/ansible/template/__init__.py", line 481, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.6/site-packages/ansible/template/__init__.py", line 717, in do_template
    res = j2_concat(rf)
  File "<template>", line 8, in root
  File "/usr/lib/python2.6/site-packages/Jinja2-2.6-py2.6.egg/jinja2/runtime.py", line 180, in call
    return __obj(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/ansible/template/__init__.py", line 615, in _lookup
    instance = self._lookup_loader.get(name.lower(), loader=self._loader, templar=self)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/loader.py", line 366, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/loader.py", line 345, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/usr/lib/python2.6/site-packages/ansible/plugins/lookup/hashi_vault.py", line 96, in <module>
    import hvac
  File "/usr/lib/python2.6/site-packages/hvac/__init__.py", line 1, in <module>
    from hvac.v1 import Client
  File "/usr/lib/python2.6/site-packages/hvac/v1/__init__.py", line 1111
    headers = json.dumps({k: [request.headers[k]] for k in request.headers})
                                                    ^
SyntaxError: invalid syntax

localhost | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

To solve this issue I had to downgrade `hvac` to version 0.5.0

**Comment by jeffwecan** [comment]
@zhogov: Unfortunately, we have no intention to support Python 2.6 generally with this module. (Though we could probably stand to make that more explicit if its not already explicitly stated.) So I don't expect we would modify the offending line unless there was some other compelling reason to do so.

For what its worth, it looks like we could do something like this to achieve the same sort of dictionary comprehension with Python 2.6 compatibility:

```
# Python 2.7+:
In [15]: {k: [request.headers[k]] for k in request.headers}
Out[15]:
{'Content-Type': ['application/x-www-form-urlencoded; charset=utf-8'],
 'Host': ['sts.amazonaws.com']}

# Python 2.6:
In [16]: dict((k, [v]) for k, v in request.headers.iteritems())
Out[16]:
{'Content-Type': ['application/x-www-form-urlencoded; charset=utf-8'],
 'Host': ['sts.amazonaws.com']}

```

**Comment by jeffwecan** [comment]
Though upon reading https://www.vaultproject.io/api/auth/aws/index.html#iam_request_headers I'm not certain we need the dictionary comprehension in the first place. In particular the highlighted statement is attempting to inserting every value from a dictionary of request headers into a single-member list while the documentation reads.

> The JSON serialization assumes that each header key maps to either a string value ***or*** an array of string values (though the length of that array will probably only be one).

(emphasis mine)

If I can verify that the statement isn't needed in the first place, we could see about dropping it.

**Comment by layer3switch** [comment]
I understand the compatibility issue with Python 2.6 going forward however #291 specifically addresses some of issue hvac==0.5.0 being deployed onto platforms running within Python 2.6 eco system, not to mention inconsistent usage of ```format``` syntax throughout the code. Can you address this as well?

**Comment by kaypeter87** [comment]
@briantist close please

**Comment by briantist** [comment]
Python 2 support was dropped in #819
