### ISSUE TITLE
Occasional Failure of travis-ci Jobs

### ISSUE THREAD

**Issue by jeffwecan** [hvac/hvac#296]
While the root cause is unknown at the time of this issue's creation, it is worth noting that travis-ci jobs for this repo occasionally fail waiting for the Vault server to start for integration tests. E.g.: https://travis-ci.org/hvac/hvac/jobs/443905728. They typically work upon a rebuild. The resolution may require increasing the time we wait for the Vault server processes to start to work around intermittent constraints on resources / etc. in a given CI/CD environment.

**Comment by jeffwecan** [comment]
Current known issue is this deal: https://travis-ci.org/hvac/hvac/jobs/472168613 =>

```
py27 runtests: commands[0] | nosetests -s --with-coverage --cover-package=hvac --cover-html
.............................................................Gateway server started on port 25333!
.........................S............................................SSSS........SSSSSS....SS...SSS......SSS..............SS..SS..............................................................................E......................................S............................SS...............................................................................................................................................................................................................................................
======================================================================
ERROR: test_undelete_secret_versions_3_successful_undelete_two_out_of_two_versions_written (tests.integration_tests.api.secrets_engines.test_kv_v2.TestKvV2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/hvac/hvac/.tox/py27/lib/python2.7/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/travis/build/hvac/hvac/tests/integration_tests/api/secrets_engines/test_kv_v2.py", line 348, in test_undelete_secret_versions
    mount_point=self.DEFAULT_MOUNT_POINT
  File "/home/travis/build/hvac/hvac/hvac/api/secrets_engines/kv_v2.py", line 122, in create_or_update_secret
    json=params,
  File "/home/travis/build/hvac/hvac/hvac/adapters.py", line 106, in post
    return self.request('post', url, **kwargs)
  File "/home/travis/build/hvac/hvac/hvac/adapters.py", line 276, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/home/travis/build/hvac/hvac/hvac/utils.py", line 29, in raise_for_error
    raise exceptions.InvalidRequest(message, errors=errors)
InvalidRequest: Uprading from non-versioned to versioned data. This backend will be unavailable for a brief period and will resume service shortly.
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): localhost:8200
urllib3.connectionpool: DEBUG: https://localhost:8200 "POST /v1/sys/mounts/kvv2 HTTP/1.1" 204 0
urllib3.connectionpool: DEBUG: https://localhost:8200 "POST /v1/kvv2/data/hvac HTTP/1.1" 400 147

```
