### ISSUE TITLE
AWS EC2 Auth:`NameError: name 'load_vault_token' is not defined`

### ISSUE THREAD

**Issue by kawsark** [hvac/hvac#333]
For the AWS EC2 Authentication Method I get the following error:
```
Traceback (most recent call last):
  File "hvactest.py", line 145, in <module>
    authenticated_vault_client = get_vault_client(verify_certs=False, ec2_role="dev-role")
  File "hvactest.py", line 137, in get_vault_client
    vault_client.token = load_vault_token(vault_client, ec2_role=ec2_role)
NameError: name 'load_vault_token' is not defined
```
This is expected because `load_vault_token` is not defined: 
```
vault_client.token = load_vault_token(vault_client, ec2_role=ec2_role)
```

**Comment by jeffwecan** [comment]
For what it is worth, this is the implementation for the aforementioned undefined method that was related to the documented example code:

```python
def load_vault_token(vault_client, ec2_role=None):
    """
    Retrieves a vault token, first from a "VAULT_TOKEN" env var if available. If this env var is unavailable, we use a
    Vault authentication backend to retrieve a token (currently limited to AWS EC2 authentication)
    :param vault_client: hvac.Client
    :param ec2_role: str, Name of the Vault AWS auth backend role to use when retrieving a token (if applicable)
    :return: string, a vault token
    """
    vault_token = os.environ.get('VAULT_TOKEN')
    if vault_token is None and ec2_role is not None:
        auth_ec2_resp = auth_ec2(
            vault_client=vault_client,
            role=ec2_role,
        )
        logger.debug('auth_ec2_resp:\n{}'.format(auth_ec2_resp))
        vault_token = auth_ec2_resp['auth']['client_token']
    return vault_token
```

(Note: this specific implementation obviously is keyed on the AWS EC2 auth method as its default source for a Vault token.)

That said, I figure this card could cover two potential issues:

* Truing up the example documentation so that it can be executed without too much additional intervention
* Updating hvac's documentation CI/CD pipeline to include the [testing of documentation](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html)

With that said, apologies for the delay in responding to this issue and we'll try to implement resolution to the two action items raised as soon as possible!
