### ISSUE TITLE
Error on importing hvac > module 'token' has no attribute '__all__'

### ISSUE THREAD

**Issue by ralberich** [hvac/hvac#359]
Ok this is a first for me, hoping I did not do anything wrong.

I'm getting an error on simply importing hvac on Python 3.7.0

- Running on windows / using powershell inside vscode
- Running inside a virtualenv
- installed successfully hvac using `pip install --upgrade hvac` > (0.7.1)
- Just created a file with 

```
import hvac

print("test")
```

Crashes with this error stack

```
File ".\proto_dcg\services\vault.py", line 1, in <module>
    import hvac
  File "C:\Users\j65374\Documents\Outils\GIT\falcon-api-test -ext\env\lib\site-packages\hvac\__init__.py", line 1,
in <module>
    from hvac.v1 import Client
  File "C:\Users\j65374\Documents\Outils\GIT\falcon-api-test -ext\env\lib\site-packages\hvac\v1\__init__.py", line
6, in <module>
    from hvac import aws_utils, exceptions, adapters, utils, api
  File "C:\Users\j65374\Documents\Outils\GIT\falcon-api-test -ext\env\lib\site-packages\hvac\aws_utils.py", line 4, in <module>
    import requests
  File "C:\Users\j65374\Documents\Outils\GIT\falcon-api-test -ext\env\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\j65374\Documents\Outils\GIT\falcon-api-test -ext\env\lib\site-packages\urllib3\__init__.py", line
8, in <module>
    from .connectionpool import (
  File "C:\Users\j65374\Documents\Outils\GIT\falcon-api-test -ext\env\lib\site-packages\urllib3\connectionpool.py", line 3, in <module>
    import logging
  File "C:\Users\j65374\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "C:\Users\j65374\AppData\Local\Programs\Python\Python37-32\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\Users\j65374\AppData\Local\Programs\Python\Python37-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Users\j65374\AppData\Local\Programs\Python\Python37-32\lib\tokenize.py", line 41, in <module>
    __all__ = token.__all__ + ["tokenize", "detect_encoding",
AttributeError: module 'token' has no attribute '__all__'
```

Am I missing something?
Is hvac not compatible with python 3.7?

**Comment by jeffwecan** [comment]
I wasn't able to replicate this issue with python 3.7.1, hvac 0.7.1, on OSX 10.14.2 at the very least:

Setting up a temp virtualenv:
```
$ mktmpenv -p python3
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/jeffrey.hogan/.virtualenvs/tmp-92195645e56da8d4/bin/python3.7
Also creating executable in /Users/jeffrey.hogan/.virtualenvs/tmp-92195645e56da8d4/bin/python
Installing setuptools, pip, wheel...
done.
virtualenvwrapper.user_scripts creating /Users/jeffrey.hogan/.virtualenvs/tmp-92195645e56da8d4/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/jeffrey.hogan/.virtualenvs/tmp-92195645e56da8d4/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/jeffrey.hogan/.virtualenvs/tmp-92195645e56da8d4/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/jeffrey.hogan/.virtualenvs/tmp-92195645e56da8d4/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/jeffrey.hogan/.virtualenvs/tmp-92195645e56da8d4/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
 tmp-92195645e56da8d4  jeffrey.hogan  ~/.virtualenvs/tmp-92195645e56da8d4 
$ python --version
Python 3.7.1
 tmp-92195645e56da8d4  jeffrey.hogan  ~/.virtualenvs/tmp-92195645e56da8d4 
$ python
Python 3.7.1 (default, Nov  6 2018, 18:45:35)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hvac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'hvac'
>>>
 tmp-92195645e56da8d4  jeffrey.hogan  ~/.virtualenvs/tmp-92195645e56da8d4 
$ pip install hvac
Collecting hvac
  Downloading https://files.pythonhosted.org/packages/7c/5e/84b3fdb96635c3011519350fc75a0ac7dd6b8415bd0e7e70051a8a8c2ffd/hvac-0.7.1-py2.py3-none-any.whl (159kB)
    100% |████████████████████████████████| 163kB 3.0MB/s
Collecting requests>=2.7.0 (from hvac)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.7.0->hvac)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.7.0->hvac)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.7.0->hvac)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.7.0->hvac)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Installing collected packages: chardet, certifi, urllib3, idna, requests, hvac
Successfully installed certifi-2018.11.29 chardet-3.0.4 hvac-0.7.1 idna-2.8 requests-2.21.0 urllib3-1.24.1
 tmp-92195645e56da8d4  jeffrey.hogan  ~/.virtualenvs/tmp-92195645e56da8d4 
```

Attempting to replicate:
```
$ python
Python 3.7.1 (default, Nov  6 2018, 18:45:35)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hvac
>>> print("test")
test
>>>
```

Similar issues, such as https://github.com/Microsoft/vscode-python/issues/706, lead me to believe it is more an issue with something named `token` in _another_ module / source file (i.e., not hvac).  Do you happen to have a file named something like `token.py` in your local python path or otherwise?

**Comment by ralberich** [comment]
A token.py file was indeed created in my project.

Thanks for this reply & happy new year !
