### ISSUE TITLE
hvac exceptions Forbidden permission denied (Python HVAC client permission denied)

### ISSUE THREAD

**Issue by nagcassandra** [hvac/hvac#422]
Hello Team,

I am facing the below error while trying to read the secrets from vault through Python code.

Making connection to vault host: https://vault.or1.adobe.net
<hvac.v1.Client object at 0x7f1b3db5dd10>
Traceback (most recent call last):
  File "vault_004.py", line 32, in <module>
    value_01 = vault_get("nag")
  File "vault_004.py", line 17, in vault_get
    result = client.read('secrets/cubbyhole/{}'.format(name))
  File "/usr/lib/python2.7/site-packages/hvac/v1/__init__.py", line 195, in read
    return self._adapter.get('/v1/{0}'.format(path), wrap_ttl=wrap_ttl).json()
  File "/usr/lib/python2.7/site-packages/hvac/adapters.py", line 93, in get
    return self.request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/hvac/adapters.py", line 276, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/usr/lib/python2.7/site-packages/hvac/utils.py", line 33, in raise_for_error
    raise exceptions.Forbidden(message, errors=errors)
hvac.exceptions.Forbidden: permission denied

I tried to create new policy to overcome the issue but there are i am getting permission denied error.

[root@or1010050159026 vault]# ../vault policy read my-policy
Error reading policy named my-policy: Error making API request.

URL: GET https://vault.or1.adobe.net/v1/sys/policies/acl/my-policy
Code: 403. Errors:

* 1 error occurred:

* permission denied
[root@or1010050159026 vault]# ../vault policy write my-policy policy.hcl
Error uploading policy: Error making API request.

URL: PUT https://vault.or1.adobe.net/v1/sys/policies/acl/my-policy
Code: 403. Errors:

* 1 error occurred:

* permission denied

policy.hcl:
# This section grants all access on "secret/*". Further restrictions can be
# applied to this broad policy, as shown below.
path "secret/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

Can some help me to resolve the issue.

Thanks
Nagendra

**Comment by smckellips** [comment]
I encountered the same issue, also against vault_host = "https://vault.or1.XXXX.net".
Calling the read method with only path returned permission denied:
```
secret = 'secrets/secret_name'
value = client.secrets.kv.v2.read_secret_version(path=secret)
```
I had to use mount_point and path in order to get a result.
```
mount_point, secret_path = secret.split('/', 1)
value = client.secrets.kv.v2.read_secret_version(
    mount_point=mount_point, path=secret_path)
```
It seems the way we've defined our policies requires the distinction.
