### ISSUE TITLE
Hvac accepts a session that is not a requests Session

### ISSUE THREAD

**Issue by surfer190** [hvac/hvac#499]
This may be expected functionality, but you can send a dict as the session

Recreate with:

```
import hvac

session = {'hello': 'world'}
client = hvac.Client(session=session)

print(client.is_authenticated())
```

Version of hvac: `hvac==0.9.3`

Can we add a check to ensure that the session is an instance of `requests.Session`?

**Comment by jeffwecan** [comment]
Yeah agreed that behavior is a bit funky. Adding a conditional to validate the correct class / parent class seems reasonable.

**Comment by surfer190** [comment]
Running this code now gives:

    Traceback (most recent call last):
      File "/hvac_bug/check.py", line 5, in <module>
        client = hvac.Client(session=session)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/hvac_bug/env/lib/python3.11/site-packages/hvac/v1/__init__.py", line 136, in __init__
        self._adapter = adapter(
                        ^^^^^^^^
      File "/hvac_bug/env/lib/python3.11/site-packages/hvac/adapters.py", line 95, in __init__
        if session.verify:
           ^^^^^^^^^^^^^^
    AttributeError: 'dict' object has no attribute 'verify'

This is not a bug but nice to raise exception informing user they are not using the package correctly.

Something like:

```
if not isinstance(session, requests.Session):
    raise TypeError("hvac session is expected to by of type 'requests.Session'")
```
