### ISSUE TITLE
Test errors during setUpClass leave vault instance running

### ISSUE THREAD

**Issue by llamasoft** [hvac/hvac#530]
If an integration test fails during a setUpClass call, the resulting vault instance is never terminated.  This causes all subsequent integration tests to fail because they expect to be interacting with an uninitialized vault instance.

For example, this is the first integration test to failure was caused by not having Java installed in my Docker image.  (Related to #529)

```
======================================================================
ERROR: test suite for <class 'tests.integration_tests.api.auth_methods.test_ldap.TestLdap'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/hvac/tests/integration_tests/api/auth_methods/test_ldap.py", line 22, in setUpClass
    cls.ldap_server = MockLdapServer()
  File "/hvac/tests/utils/mock_ldap_server.py", line 64, in __init__
    'entries': self.ldap_entries,
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/ldap_test/server.py", line 202, in __init__
    SERVER_PROCESS = run_jvm_server(java_gateway_port)
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/ldap_test/server.py", line 72, in run_jvm_server
    raise Exception("'java' executable not found in system path!")
Exception: 'java' executable not found in system path!
```

From this point forward, all of the remaining integration tests fail on the following:

```
Traceback (most recent call last):
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/hvac/.tox/py27/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/hvac/tests/integration_tests/api/auth_methods/test_mfa.py", line 17, in setUpClass
    super(TestMfa, cls).setUpClass()
  File "/hvac/tests/utils/hvac_integration_test_case.py", line 44, in setUpClass
    cls.manager.initialize()
  File "/hvac/tests/utils/server_manager.py", line 109, in initialize
    assert not self.client.sys.is_initialized()
AssertionError: 
```

---

Nose uses and is built on top of the unittest library.  The [documentation for it](https://docs.python.org/2/library/unittest.html#organizing-test-code) has the following tiny blub on the subject:

> If setUp() succeeded, the tearDown() method will be run whether runTest() succeeded or not.

The implication here is that if setUp _didn't_ succeed then tearDown _isn't_ called.  This took me by surprise, but it turns out [I wasn't the only one](https://bugs.python.org/issue5538).

I'll start working on a fix for this.

**Comment by jeffwecan** [comment]
Thanks again @llamasoft! Been meaning to get this issue resolved for quite some time... 🙃

**Comment by llamasoft** [comment]
This is going to sound silly but hear me out: if the Vault executable can't be found, should the integration tests be skipped or an error?

Arguments in favor of throwing an error:
- The tests' responsibility is to test the library, not your execution environment.
- Integration tests are fundamental in testing if the library actually works.
- Skipping tests gives no feedback and may give the false sense of correctness.

Arguments in favor of skipping:
- It's a waste of time to run a test that you know will fail.
- The Vault executable isn't required to use this project so it shouldn't be required to run the tests.
  - Skipping the LDAP integration test because Java is missing (#529) is reasonable.
- The Consul executable isn't required to use this project and Consul related tests are [silently skipped](https://github.com/hvac/hvac/blob/7485853b99c67375d7a1c6a191f68ca1f8321064/tests/utils/hvac_integration_test_case.py#L26-L28) if it's not available.
- We already skip or modify certain tests to avoid known issues:
  - Some integration tests are skipped based on the available Vault version.
  - Test execution is modified when using the Enterprise version of Vault.

Other thoughts:
- Test environments are provisioned by the project's test ecosystem (i.e. make, tox, and Travis) so they're already partially responsible for making sure the test environments meet certain standards.
  - If the test environments provision Vault/Consul, it can better control the version it's testing against.
  - Obviously the provisioned Vault/Consul binaries shouldn't be outside the project's directory.  If the helper scripts are to be used, they'll require some modification.
- External dependencies are icky, even for testing.  However, it seems reasonable to require that Vault be available for testing given this project's purpose.
