### ISSUE TITLE
ImportError: No module named hvac

### ISSUE THREAD

**Issue by gowthamakanthan** [hvac/hvac#561]
Team,

I have installed "ansible-modules-hashivault", "hvac"  using pip. And created a playbook to enable a secret. Getting below import error. Have validated the packages list in the pip and all the packages are installed. I am using python 2.7. Any leads?

**Comment by jeffwecan** [comment]
Howdy @gowthamakanthan, I don't see any error output attached. If you can include some additional details I'd be happy to try to help sort out what is occurring.

**Comment by drewmullen** [comment]
PATH can often get messed up with ansible if youre using a virtualenv. if you are using a venv, try:

1. `deactivate` (return to system python)
2. `pip remove ansible hvac ansible-modules-hashivault`
3. `source <myvenv>/bin/activate` (use your venv)
4. `pip install ansible hvac ansible-modules-hashivault`

**Comment by gowthamakanthan** [comment]
Thank you for your reply. Please check below for the details:

Package list:
`pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020.
Please upgrade your Python as Python 2.7 is no longer maintained. A future
version of pip will drop support for Python 2.7. More details about Python
2 support in pip, can be found at
https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                      Version
---------------------------- --------
ansible                      2.7.10
ansible-modules-hashivault   4.2.3
Babel                        0.9.6
backports.ssl-match-hostname 3.5.0.1
certifi                      2019.3.9
cffi                         1.6.0
chardet                      3.0.4
configobj                    4.7.2
cryptography                 1.7.2
decorator                    3.4.0
enum34                       1.0.4
httplib2                     0.9.2
hvac                         0.10.0`

Error:
`The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_hashivault_secret_engine_payload_kRLFx4/__main__.py",
line 2, in <module>
  File
"/tmp/ansible_hashivault_secret_engine_payload_kRLFx4/ansible_hashivault_secret_engine_payload.zip/ansible/module_utils/hashivault.py",
line 4, in <module>
ImportError: No module named hvac

fatal: [10.9.123.21]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File
\"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in
_ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File
\"/tmp/ansible_hashivault_secret_engine_payload_kRLFx4/__main__.py\", line
2, in <module>\n  File
\"/tmp/ansible_hashivault_secret_engine_payload_kRLFx4/ansible_hashivault_secret_engine_payload.zip/ansible/module_utils/hashivault.py\",
line 4, in <module>\nImportError: No module named hvac\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}`
---
Best regards,
Gowtham
07798838879


=====================
Learn from mistakes....

Please consider the environment before printing this email - Thanks

**Comment by drewmullen** [comment]
let me know what you think from my comment. also please be advised that python 2 is no longer a supported language, you should migrate to python3 asap: https://www.infoq.com/news/2019/09/python-2-end-of-life-approaching/

**Comment by grzegorznowak** [comment]
Yeah just had the same issue @gowthamakanthan .

The problem is lack of the package on a remote machine not your host. This should fix it assuming package/pip versions match your environment:

```
- name: Install pip for more dependencies down the line
  apt:
    pkg:
      - python3-pip
      - python-setuptools
    state: present
    update-cache: yes
    install_recommends: no
    cache_valid_time: 3600

- name: Install pips for vault module
  pip:
    name:
      - hvac==0.10.8
    executable: pip3
```

**Comment by jamesbraza** [comment]
@grzegorznowak with your above comment:

> ```yaml
>   apt:
>     pkg:
>       - python3-pip
>       - python-setuptools
> ```

 I think this should have `python3-setuptools` not `python-setuptools` (which is Python 2)
