### ISSUE TITLE
hvac import fails

### ISSUE THREAD

**Issue by richardsamuelk** [hvac/hvac#706]
installed hvac-

Response:
**sudo pip install 'hvac[parser]'
**Requirement** already satisfied: hvac[parser] in /usr/local/lib/python2.7/site-packages**

hvac (0.10.12)

python version-
Python 2.7.18 (default, Feb 18 2021, 06:10:44) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2

error- 
>>> import hvac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/hvac/__init__.py", line 1, in <module>
    from hvac.v1 import Client
  File "/usr/local/lib/python2.7/site-packages/hvac/v1/__init__.py", line 7, in <module>
    from hvac import aws_utils, exceptions, adapters, utils, api
  File "/usr/local/lib/python2.7/site-packages/hvac/api/__init__.py", line 2, in <module>
    from hvac.api.auth_methods import AuthMethods
  File "/usr/local/lib/python2.7/site-packages/hvac/api/auth_methods/__init__.py", line 18, in <module>
    from hvac.api.auth_methods.cert import Cert
  File "/usr/local/lib/python2.7/site-packages/hvac/api/auth_methods/cert.py", line 244
    **self._adapter._kwargs,
     ^
SyntaxError: invalid syntax

**Comment by sealneaward** [comment]
Getting the same issue with the new release.

**Comment by NeillAlexander** [comment]
Hitting the same issue. It looks like it's a Python2/Python3 thing.
```
[root@xxx auth_methods]# python3 -m py_compile cert.py 
[root@xxx auth_methods]# python2 -m py_compile cert.py 
  File "cert.py", line 244
    **self._adapter._kwargs,
     ^
SyntaxError: invalid syntax
```
I didn't see anything in release notes about dropping support for Python2.
