### ISSUE TITLE
check_header_validity failing for k8s auth

### ISSUE THREAD

**Issue by vikulaggarwal** [hvac/hvac#799]
I'm upgrading from hvac 0.9.5 to 0.11.2. header validity check is failing for me and I get the following exception:

```
Traceback (most recent call last):
  File "/home/app/py38venv/lib64/python3.8/site-packages/requests/utils.py", line 977, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

File "/home/app/py38venv/lib64/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/app/py38venv/lib64/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/app/py38venv/lib64/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/home/app/py38venv/lib64/python3.8/site-packages/requests/models.py", line 451, in prepare_headers
    check_header_validity(header)
  File "/home/app/py38venv/lib64/python3.8/site-packages/requests/utils.py", line 980, in check_header_validity
    raise InvalidHeader("Value for header {%s: %s} must be of type str or "
requests.exceptions.InvalidHeader: Value for header {X-Vault-Token: <class 'NotImplementedError'>} must be of type str or bytes, not <class 'type'>
```

**Comment by vikulaggarwal** [comment]
This used to work in 0.9.5 without any issues.

**Comment by vikulaggarwal** [comment]
I switched from using the abstract class Adapter to JSONAdapter, I'm now getting the following exception:

```
  File "/home/app/py38venv/lib64/python3.8/site-packages/hvac/utils.py", line 201, in new_func
    return method(*args, **kwargs)
  File "/home/app/py38venv/lib64/python3.8/site-packages/hvac/v1/__init__.py", line 2004, in auth_kubernetes
    return self.login(url, json=params, use_token=use_token)
  File "/home/app/py38venv/lib64/python3.8/site-packages/hvac/v1/__init__.py", line 1495, in login
    return self._adapter.login(url=url, use_token=use_token, **kwargs)
  File "/home/app/py38venv/lib64/python3.8/site-packages/hvac/adapters.py", line 200, in login
    self.token = self.get_login_token(response)
  File "/home/app/py38venv/lib64/python3.8/site-packages/hvac/adapters.py", line 352, in get_login_token
    return response["auth"]["client_token"]
TypeError: 'Response' object is not subscriptable
```
