### ISSUE TITLE
Login using Azure AD JWT Token

### ISSUE THREAD

**Issue by sknopp** [hvac/hvac#985]
Hi there,

I'm currently trying to build a collection of small administrative scripts using hvac to integrate approles into our project creation processes.
I've used the spare documentation on howto authenticate correctly but unfortunately i'm always getting the following error:

```
Traceback (most recent call last):
  File "/home/sebastian/Projektcode/tools/py.vault_auth.approle.example/./vault-auth-approle-example/main_approle_create.py", line 25, in <module>
    client.auth.azure.login(
  File "/home/sebastian/.local/lib/python3.10/site-packages/hvac/api/auth_methods/azure.py", line 339, in login
    return self._adapter.login(
  File "/home/sebastian/.local/lib/python3.10/site-packages/hvac/adapters.py", line 194, in login
    response = self.post(url, **kwargs)
  File "/home/sebastian/.local/lib/python3.10/site-packages/hvac/adapters.py", line 123, in post
    return self.request("post", url, **kwargs)
  File "/home/sebastian/.local/lib/python3.10/site-packages/hvac/adapters.py", line 372, in request
    response = super().request(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.10/site-packages/hvac/adapters.py", line 340, in request
    self._raise_for_error(method, url, response)
  File "/home/sebastian/.local/lib/python3.10/site-packages/hvac/adapters.py", line 258, in _raise_for_error
    utils.raise_for_error(
  File "/home/sebastian/.local/lib/python3.10/site-packages/hvac/utils.py", line 41, in raise_for_error
    raise exceptions.VaultError.from_status(
hvac.exceptions.InvalidRequest: role with oidc role_type is not allowed, on post https://vault.redacted.server.domain/v1/auth/oidc/login
```

Attached you find the related script. (see [documentation](https://hvac.readthedocs.io/en/stable/usage/auth_methods/azure.html#login))

```python3
#!/usr/bin/env python3
import hvac
import logging
from azure.identity import DefaultAzureCredential


logger = logging.getLogger(__name__)

VAULT_URL = "https://vault.redacted.server.domain"
AZURE_APP_ID = "<REDACTED>"
AZURE_TENANT_ID = "<REDACTED>"

credential = DefaultAzureCredential(
    logging_enable=True,
    managed_identity_client_id=AZURE_APP_ID,
    interactive_browser_client_id=AZURE_APP_ID,
    interactive_browser_tenant_id=AZURE_TENANT_ID,
    exclude_environment_credential=True, 
    exclude_managed_identity_credential=True,
    exclude_interactive_browser_credential=False,
    exclude_powershell_credential=True
)

client = hvac.Client(url=VAULT_URL)
client.auth.azure.login(
    mount_point="oidc",
    role="", 
    jwt=credential.get_token("https://graph.microsoft.com/.default")[0],
    use_token=True
)

client.auth.approle.create_or_update_approle(
    role_name='testclient2',
    token_policies=['kv-minimal'],
    token_ttl="10m",
    token_max_ttl="15m",
    period=0
)
```

Seems like the vault web frontend [had the same issue some time ago](https://github.com/hashicorp/vault/issues/14671) but i was not able to work out what the solution was there in the end...
Any help is greatly appreciated.

**Comment by briantist** [comment]
Hi @sknopp , are you still having this issue?

The exception being raised is directly based on the response being received from the Vault server, so I'm not sure if this is an issue within `hvac` or not.

The Vault issue you linked seems to have been something that affected the UI only, so it is probably not related to this.

Are you able to successfully login with any other method using the same credentials, like through the Vault UI, Vault CLI, `curl`/`Invoke-RestMethod`/`Invoke-WebRequest`, etc.?
